// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7CvDs8jJP225mxza79n4hFarusSQLMA',
    appId: '1:222820582163:web:d6bf595ca85cd0f30bd0e6',
    messagingSenderId: '222820582163',
    projectId: 'market-krh',
    authDomain: 'market-krh.firebaseapp.com',
    storageBucket: 'market-krh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePOOLsYJen4CtM5nbkhVGu6JJHzy8GRg',
    appId: '1:222820582163:android:32ea87e914fc1ecc0bd0e6',
    messagingSenderId: '222820582163',
    projectId: 'market-krh',
    storageBucket: 'market-krh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgDtlWpyT08mjs7Letc9D7qNAOq-inXA',
    appId: '1:222820582163:ios:0d0d0fbac0c519db0bd0e6',
    messagingSenderId: '222820582163',
    projectId: 'market-krh',
    storageBucket: 'market-krh.firebasestorage.app',
    iosBundleId: 'com.example.fruitesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgDtlWpyT08mjs7Letc9D7qNAOq-inXA',
    appId: '1:222820582163:ios:0d0d0fbac0c519db0bd0e6',
    messagingSenderId: '222820582163',
    projectId: 'market-krh',
    storageBucket: 'market-krh.firebasestorage.app',
    iosBundleId: 'com.example.fruitesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE7CvDs8jJP225mxza79n4hFarusSQLMA',
    appId: '1:222820582163:web:4b03ee38b57caa1b0bd0e6',
    messagingSenderId: '222820582163',
    projectId: 'market-krh',
    authDomain: 'market-krh.firebaseapp.com',
    storageBucket: 'market-krh.firebasestorage.app',
  );
}
